#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriGoals
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NutriGoals")]
	public partial class NutriGoalsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertActividadFisica(ActividadFisica instance);
    partial void UpdateActividadFisica(ActividadFisica instance);
    partial void DeleteActividadFisica(ActividadFisica instance);
    partial void InsertEjercicio(Ejercicio instance);
    partial void UpdateEjercicio(Ejercicio instance);
    partial void DeleteEjercicio(Ejercicio instance);
    partial void InsertListaIngrediente(ListaIngrediente instance);
    partial void UpdateListaIngrediente(ListaIngrediente instance);
    partial void DeleteListaIngrediente(ListaIngrediente instance);
    partial void InsertReceta(Receta instance);
    partial void UpdateReceta(Receta instance);
    partial void DeleteReceta(Receta instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertObjetivosNutricionale(ObjetivosNutricionale instance);
    partial void UpdateObjetivosNutricionale(ObjetivosNutricionale instance);
    partial void DeleteObjetivosNutricionale(ObjetivosNutricionale instance);
    partial void InsertUserMetrica(UserMetrica instance);
    partial void UpdateUserMetrica(UserMetrica instance);
    partial void DeleteUserMetrica(UserMetrica instance);
    partial void InsertAlimento(Alimento instance);
    partial void UpdateAlimento(Alimento instance);
    partial void DeleteAlimento(Alimento instance);
    partial void InsertAlimentoIngerido(AlimentoIngerido instance);
    partial void UpdateAlimentoIngerido(AlimentoIngerido instance);
    partial void DeleteAlimentoIngerido(AlimentoIngerido instance);
    #endregion
		
		public NutriGoalsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NutriGoalsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NutriGoalsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NutriGoalsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ActividadFisica> ActividadFisicas
		{
			get
			{
				return this.GetTable<ActividadFisica>();
			}
		}
		
		public System.Data.Linq.Table<Ejercicio> Ejercicios
		{
			get
			{
				return this.GetTable<Ejercicio>();
			}
		}
		
		public System.Data.Linq.Table<ListaIngrediente> ListaIngredientes
		{
			get
			{
				return this.GetTable<ListaIngrediente>();
			}
		}
		
		public System.Data.Linq.Table<Receta> Recetas
		{
			get
			{
				return this.GetTable<Receta>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<ObjetivosNutricionale> ObjetivosNutricionales
		{
			get
			{
				return this.GetTable<ObjetivosNutricionale>();
			}
		}
		
		public System.Data.Linq.Table<UserMetrica> UserMetricas
		{
			get
			{
				return this.GetTable<UserMetrica>();
			}
		}
		
		public System.Data.Linq.Table<Alimento> Alimentos
		{
			get
			{
				return this.GetTable<Alimento>();
			}
		}
		
		public System.Data.Linq.Table<AlimentoIngerido> AlimentoIngeridos
		{
			get
			{
				return this.GetTable<AlimentoIngerido>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ActividadFisica")]
	public partial class ActividadFisica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdActFisica;
		
		private int _FKIdUsuario;
		
		private int _FKIdEjercicio;
		
		private System.DateTime _FechaHora;
		
		private decimal _TiempoMinutos;
		
		private decimal _CaloriasTotales;
		
		private EntityRef<Ejercicio> _Ejercicio;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdActFisicaChanging(int value);
    partial void OnIdActFisicaChanged();
    partial void OnFKIdUsuarioChanging(int value);
    partial void OnFKIdUsuarioChanged();
    partial void OnFKIdEjercicioChanging(int value);
    partial void OnFKIdEjercicioChanged();
    partial void OnFechaHoraChanging(System.DateTime value);
    partial void OnFechaHoraChanged();
    partial void OnTiempoMinutosChanging(decimal value);
    partial void OnTiempoMinutosChanged();
    partial void OnCaloriasTotalesChanging(decimal value);
    partial void OnCaloriasTotalesChanged();
    #endregion
		
		public ActividadFisica()
		{
			this._Ejercicio = default(EntityRef<Ejercicio>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdActFisica", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdActFisica
		{
			get
			{
				return this._IdActFisica;
			}
			set
			{
				if ((this._IdActFisica != value))
				{
					this.OnIdActFisicaChanging(value);
					this.SendPropertyChanging();
					this._IdActFisica = value;
					this.SendPropertyChanged("IdActFisica");
					this.OnIdActFisicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKIdUsuario", DbType="Int NOT NULL")]
		public int FKIdUsuario
		{
			get
			{
				return this._FKIdUsuario;
			}
			set
			{
				if ((this._FKIdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._FKIdUsuario = value;
					this.SendPropertyChanged("FKIdUsuario");
					this.OnFKIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKIdEjercicio", DbType="Int NOT NULL")]
		public int FKIdEjercicio
		{
			get
			{
				return this._FKIdEjercicio;
			}
			set
			{
				if ((this._FKIdEjercicio != value))
				{
					if (this._Ejercicio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKIdEjercicioChanging(value);
					this.SendPropertyChanging();
					this._FKIdEjercicio = value;
					this.SendPropertyChanged("FKIdEjercicio");
					this.OnFKIdEjercicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHora", DbType="DateTime NOT NULL")]
		public System.DateTime FechaHora
		{
			get
			{
				return this._FechaHora;
			}
			set
			{
				if ((this._FechaHora != value))
				{
					this.OnFechaHoraChanging(value);
					this.SendPropertyChanging();
					this._FechaHora = value;
					this.SendPropertyChanged("FechaHora");
					this.OnFechaHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TiempoMinutos", DbType="Decimal(3,0) NOT NULL")]
		public decimal TiempoMinutos
		{
			get
			{
				return this._TiempoMinutos;
			}
			set
			{
				if ((this._TiempoMinutos != value))
				{
					this.OnTiempoMinutosChanging(value);
					this.SendPropertyChanging();
					this._TiempoMinutos = value;
					this.SendPropertyChanged("TiempoMinutos");
					this.OnTiempoMinutosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaloriasTotales", DbType="Decimal(4,0) NOT NULL")]
		public decimal CaloriasTotales
		{
			get
			{
				return this._CaloriasTotales;
			}
			set
			{
				if ((this._CaloriasTotales != value))
				{
					this.OnCaloriasTotalesChanging(value);
					this.SendPropertyChanging();
					this._CaloriasTotales = value;
					this.SendPropertyChanged("CaloriasTotales");
					this.OnCaloriasTotalesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ejercicio_ActividadFisica", Storage="_Ejercicio", ThisKey="FKIdEjercicio", OtherKey="IdEjercicio", IsForeignKey=true)]
		public Ejercicio Ejercicio
		{
			get
			{
				return this._Ejercicio.Entity;
			}
			set
			{
				Ejercicio previousValue = this._Ejercicio.Entity;
				if (((previousValue != value) 
							|| (this._Ejercicio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ejercicio.Entity = null;
						previousValue.ActividadFisicas.Remove(this);
					}
					this._Ejercicio.Entity = value;
					if ((value != null))
					{
						value.ActividadFisicas.Add(this);
						this._FKIdEjercicio = value.IdEjercicio;
					}
					else
					{
						this._FKIdEjercicio = default(int);
					}
					this.SendPropertyChanged("Ejercicio");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_ActividadFisica", Storage="_Usuario", ThisKey="FKIdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.ActividadFisicas.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.ActividadFisicas.Add(this);
						this._FKIdUsuario = value.IdUsuario;
					}
					else
					{
						this._FKIdUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ejercicio")]
	public partial class Ejercicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEjercicio;
		
		private string _Nombre;
		
		private decimal _CaloriasPorMinuto;
		
		private EntitySet<ActividadFisica> _ActividadFisicas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEjercicioChanging(int value);
    partial void OnIdEjercicioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCaloriasPorMinutoChanging(decimal value);
    partial void OnCaloriasPorMinutoChanged();
    #endregion
		
		public Ejercicio()
		{
			this._ActividadFisicas = new EntitySet<ActividadFisica>(new Action<ActividadFisica>(this.attach_ActividadFisicas), new Action<ActividadFisica>(this.detach_ActividadFisicas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEjercicio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEjercicio
		{
			get
			{
				return this._IdEjercicio;
			}
			set
			{
				if ((this._IdEjercicio != value))
				{
					this.OnIdEjercicioChanging(value);
					this.SendPropertyChanging();
					this._IdEjercicio = value;
					this.SendPropertyChanged("IdEjercicio");
					this.OnIdEjercicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaloriasPorMinuto", DbType="Decimal(4,2) NOT NULL")]
		public decimal CaloriasPorMinuto
		{
			get
			{
				return this._CaloriasPorMinuto;
			}
			set
			{
				if ((this._CaloriasPorMinuto != value))
				{
					this.OnCaloriasPorMinutoChanging(value);
					this.SendPropertyChanging();
					this._CaloriasPorMinuto = value;
					this.SendPropertyChanged("CaloriasPorMinuto");
					this.OnCaloriasPorMinutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ejercicio_ActividadFisica", Storage="_ActividadFisicas", ThisKey="IdEjercicio", OtherKey="FKIdEjercicio")]
		public EntitySet<ActividadFisica> ActividadFisicas
		{
			get
			{
				return this._ActividadFisicas;
			}
			set
			{
				this._ActividadFisicas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ActividadFisicas(ActividadFisica entity)
		{
			this.SendPropertyChanging();
			entity.Ejercicio = this;
		}
		
		private void detach_ActividadFisicas(ActividadFisica entity)
		{
			this.SendPropertyChanging();
			entity.Ejercicio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ListaIngredientes")]
	public partial class ListaIngrediente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FKIdReceta;
		
		private int _FKIdAlimento;
		
		private decimal _CantidadGRMS;
		
		private EntityRef<Receta> _Receta;
		
		private EntityRef<Alimento> _Alimento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFKIdRecetaChanging(int value);
    partial void OnFKIdRecetaChanged();
    partial void OnFKIdAlimentoChanging(int value);
    partial void OnFKIdAlimentoChanged();
    partial void OnCantidadGRMSChanging(decimal value);
    partial void OnCantidadGRMSChanged();
    #endregion
		
		public ListaIngrediente()
		{
			this._Receta = default(EntityRef<Receta>);
			this._Alimento = default(EntityRef<Alimento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKIdReceta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FKIdReceta
		{
			get
			{
				return this._FKIdReceta;
			}
			set
			{
				if ((this._FKIdReceta != value))
				{
					if (this._Receta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKIdRecetaChanging(value);
					this.SendPropertyChanging();
					this._FKIdReceta = value;
					this.SendPropertyChanged("FKIdReceta");
					this.OnFKIdRecetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKIdAlimento", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FKIdAlimento
		{
			get
			{
				return this._FKIdAlimento;
			}
			set
			{
				if ((this._FKIdAlimento != value))
				{
					if (this._Alimento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKIdAlimentoChanging(value);
					this.SendPropertyChanging();
					this._FKIdAlimento = value;
					this.SendPropertyChanged("FKIdAlimento");
					this.OnFKIdAlimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadGRMS", DbType="Decimal(3,0) NOT NULL")]
		public decimal CantidadGRMS
		{
			get
			{
				return this._CantidadGRMS;
			}
			set
			{
				if ((this._CantidadGRMS != value))
				{
					this.OnCantidadGRMSChanging(value);
					this.SendPropertyChanging();
					this._CantidadGRMS = value;
					this.SendPropertyChanged("CantidadGRMS");
					this.OnCantidadGRMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Receta_ListaIngrediente", Storage="_Receta", ThisKey="FKIdReceta", OtherKey="IdReceta", IsForeignKey=true)]
		public Receta Receta
		{
			get
			{
				return this._Receta.Entity;
			}
			set
			{
				Receta previousValue = this._Receta.Entity;
				if (((previousValue != value) 
							|| (this._Receta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Receta.Entity = null;
						previousValue.ListaIngredientes.Remove(this);
					}
					this._Receta.Entity = value;
					if ((value != null))
					{
						value.ListaIngredientes.Add(this);
						this._FKIdReceta = value.IdReceta;
					}
					else
					{
						this._FKIdReceta = default(int);
					}
					this.SendPropertyChanged("Receta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alimento_ListaIngrediente", Storage="_Alimento", ThisKey="FKIdAlimento", OtherKey="IdAlimento", IsForeignKey=true)]
		public Alimento Alimento
		{
			get
			{
				return this._Alimento.Entity;
			}
			set
			{
				Alimento previousValue = this._Alimento.Entity;
				if (((previousValue != value) 
							|| (this._Alimento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alimento.Entity = null;
						previousValue.ListaIngredientes.Remove(this);
					}
					this._Alimento.Entity = value;
					if ((value != null))
					{
						value.ListaIngredientes.Add(this);
						this._FKIdAlimento = value.IdAlimento;
					}
					else
					{
						this._FKIdAlimento = default(int);
					}
					this.SendPropertyChanged("Alimento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recetas")]
	public partial class Receta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdReceta;
		
		private string _Nombre;
		
		private decimal _Calorias100;
		
		private decimal _Proteinas100;
		
		private decimal _Carbohidratos100;
		
		private decimal _Grasas100;
		
		private EntitySet<ListaIngrediente> _ListaIngredientes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRecetaChanging(int value);
    partial void OnIdRecetaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCalorias100Changing(decimal value);
    partial void OnCalorias100Changed();
    partial void OnProteinas100Changing(decimal value);
    partial void OnProteinas100Changed();
    partial void OnCarbohidratos100Changing(decimal value);
    partial void OnCarbohidratos100Changed();
    partial void OnGrasas100Changing(decimal value);
    partial void OnGrasas100Changed();
    #endregion
		
		public Receta()
		{
			this._ListaIngredientes = new EntitySet<ListaIngrediente>(new Action<ListaIngrediente>(this.attach_ListaIngredientes), new Action<ListaIngrediente>(this.detach_ListaIngredientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReceta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdReceta
		{
			get
			{
				return this._IdReceta;
			}
			set
			{
				if ((this._IdReceta != value))
				{
					this.OnIdRecetaChanging(value);
					this.SendPropertyChanging();
					this._IdReceta = value;
					this.SendPropertyChanged("IdReceta");
					this.OnIdRecetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calorias100", DbType="Decimal(3,0) NOT NULL")]
		public decimal Calorias100
		{
			get
			{
				return this._Calorias100;
			}
			set
			{
				if ((this._Calorias100 != value))
				{
					this.OnCalorias100Changing(value);
					this.SendPropertyChanging();
					this._Calorias100 = value;
					this.SendPropertyChanged("Calorias100");
					this.OnCalorias100Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proteinas100", DbType="Decimal(3,0) NOT NULL")]
		public decimal Proteinas100
		{
			get
			{
				return this._Proteinas100;
			}
			set
			{
				if ((this._Proteinas100 != value))
				{
					this.OnProteinas100Changing(value);
					this.SendPropertyChanging();
					this._Proteinas100 = value;
					this.SendPropertyChanged("Proteinas100");
					this.OnProteinas100Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carbohidratos100", DbType="Decimal(3,0) NOT NULL")]
		public decimal Carbohidratos100
		{
			get
			{
				return this._Carbohidratos100;
			}
			set
			{
				if ((this._Carbohidratos100 != value))
				{
					this.OnCarbohidratos100Changing(value);
					this.SendPropertyChanging();
					this._Carbohidratos100 = value;
					this.SendPropertyChanged("Carbohidratos100");
					this.OnCarbohidratos100Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grasas100", DbType="Decimal(3,0) NOT NULL")]
		public decimal Grasas100
		{
			get
			{
				return this._Grasas100;
			}
			set
			{
				if ((this._Grasas100 != value))
				{
					this.OnGrasas100Changing(value);
					this.SendPropertyChanging();
					this._Grasas100 = value;
					this.SendPropertyChanged("Grasas100");
					this.OnGrasas100Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Receta_ListaIngrediente", Storage="_ListaIngredientes", ThisKey="IdReceta", OtherKey="FKIdReceta")]
		public EntitySet<ListaIngrediente> ListaIngredientes
		{
			get
			{
				return this._ListaIngredientes;
			}
			set
			{
				this._ListaIngredientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ListaIngredientes(ListaIngrediente entity)
		{
			this.SendPropertyChanging();
			entity.Receta = this;
		}
		
		private void detach_ListaIngredientes(ListaIngrediente entity)
		{
			this.SendPropertyChanging();
			entity.Receta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuario;
		
		private string _Email;
		
		private string _Nombre;
		
		private string _Apellido1;
		
		private string _Apellido2;
		
		private System.Data.Linq.Binary _PasswordHash;
		
		private System.Data.Linq.Binary _PasswordSalt;
		
		private EntitySet<ActividadFisica> _ActividadFisicas;
		
		private EntitySet<ObjetivosNutricionale> _ObjetivosNutricionales;
		
		private EntitySet<UserMetrica> _UserMetricas;
		
		private EntitySet<AlimentoIngerido> _AlimentoIngeridos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellido1Changing(string value);
    partial void OnApellido1Changed();
    partial void OnApellido2Changing(string value);
    partial void OnApellido2Changed();
    partial void OnPasswordHashChanging(System.Data.Linq.Binary value);
    partial void OnPasswordHashChanged();
    partial void OnPasswordSaltChanging(System.Data.Linq.Binary value);
    partial void OnPasswordSaltChanged();
    #endregion
		
		public Usuario()
		{
			this._ActividadFisicas = new EntitySet<ActividadFisica>(new Action<ActividadFisica>(this.attach_ActividadFisicas), new Action<ActividadFisica>(this.detach_ActividadFisicas));
			this._ObjetivosNutricionales = new EntitySet<ObjetivosNutricionale>(new Action<ObjetivosNutricionale>(this.attach_ObjetivosNutricionales), new Action<ObjetivosNutricionale>(this.detach_ObjetivosNutricionales));
			this._UserMetricas = new EntitySet<UserMetrica>(new Action<UserMetrica>(this.attach_UserMetricas), new Action<UserMetrica>(this.detach_UserMetricas));
			this._AlimentoIngeridos = new EntitySet<AlimentoIngerido>(new Action<AlimentoIngerido>(this.attach_AlimentoIngeridos), new Action<AlimentoIngerido>(this.detach_AlimentoIngeridos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido1", DbType="VarChar(100)")]
		public string Apellido1
		{
			get
			{
				return this._Apellido1;
			}
			set
			{
				if ((this._Apellido1 != value))
				{
					this.OnApellido1Changing(value);
					this.SendPropertyChanging();
					this._Apellido1 = value;
					this.SendPropertyChanged("Apellido1");
					this.OnApellido1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido2", DbType="VarChar(100)")]
		public string Apellido2
		{
			get
			{
				return this._Apellido2;
			}
			set
			{
				if ((this._Apellido2 != value))
				{
					this.OnApellido2Changing(value);
					this.SendPropertyChanging();
					this._Apellido2 = value;
					this.SendPropertyChanged("Apellido2");
					this.OnApellido2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHash", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PasswordHash
		{
			get
			{
				return this._PasswordHash;
			}
			set
			{
				if ((this._PasswordHash != value))
				{
					this.OnPasswordHashChanging(value);
					this.SendPropertyChanging();
					this._PasswordHash = value;
					this.SendPropertyChanged("PasswordHash");
					this.OnPasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordSalt", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PasswordSalt
		{
			get
			{
				return this._PasswordSalt;
			}
			set
			{
				if ((this._PasswordSalt != value))
				{
					this.OnPasswordSaltChanging(value);
					this.SendPropertyChanging();
					this._PasswordSalt = value;
					this.SendPropertyChanged("PasswordSalt");
					this.OnPasswordSaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_ActividadFisica", Storage="_ActividadFisicas", ThisKey="IdUsuario", OtherKey="FKIdUsuario")]
		public EntitySet<ActividadFisica> ActividadFisicas
		{
			get
			{
				return this._ActividadFisicas;
			}
			set
			{
				this._ActividadFisicas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_ObjetivosNutricionale", Storage="_ObjetivosNutricionales", ThisKey="IdUsuario", OtherKey="FKIdUsuario")]
		public EntitySet<ObjetivosNutricionale> ObjetivosNutricionales
		{
			get
			{
				return this._ObjetivosNutricionales;
			}
			set
			{
				this._ObjetivosNutricionales.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_UserMetrica", Storage="_UserMetricas", ThisKey="IdUsuario", OtherKey="FKIdUsuario")]
		public EntitySet<UserMetrica> UserMetricas
		{
			get
			{
				return this._UserMetricas;
			}
			set
			{
				this._UserMetricas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_AlimentoIngerido", Storage="_AlimentoIngeridos", ThisKey="IdUsuario", OtherKey="FKIdUsuario")]
		public EntitySet<AlimentoIngerido> AlimentoIngeridos
		{
			get
			{
				return this._AlimentoIngeridos;
			}
			set
			{
				this._AlimentoIngeridos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ActividadFisicas(ActividadFisica entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_ActividadFisicas(ActividadFisica entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_ObjetivosNutricionales(ObjetivosNutricionale entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_ObjetivosNutricionales(ObjetivosNutricionale entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_UserMetricas(UserMetrica entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_UserMetricas(UserMetrica entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_AlimentoIngeridos(AlimentoIngerido entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_AlimentoIngeridos(AlimentoIngerido entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObjetivosNutricionales")]
	public partial class ObjetivosNutricionale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdObjetivoNutricional;
		
		private int _FKIdUsuario;
		
		private System.DateTime _FechaDeEstablecimiento;
		
		private decimal _CaloriasDiaObjetivo;
		
		private decimal _ProteinasDiaObjetivo;
		
		private decimal _CarbohidratosDiaObjetivo;
		
		private decimal _GrasasDiaObjetivo;
		
		private string _Objetivo;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdObjetivoNutricionalChanging(int value);
    partial void OnIdObjetivoNutricionalChanged();
    partial void OnFKIdUsuarioChanging(int value);
    partial void OnFKIdUsuarioChanged();
    partial void OnFechaDeEstablecimientoChanging(System.DateTime value);
    partial void OnFechaDeEstablecimientoChanged();
    partial void OnCaloriasDiaObjetivoChanging(decimal value);
    partial void OnCaloriasDiaObjetivoChanged();
    partial void OnProteinasDiaObjetivoChanging(decimal value);
    partial void OnProteinasDiaObjetivoChanged();
    partial void OnCarbohidratosDiaObjetivoChanging(decimal value);
    partial void OnCarbohidratosDiaObjetivoChanged();
    partial void OnGrasasDiaObjetivoChanging(decimal value);
    partial void OnGrasasDiaObjetivoChanged();
    partial void OnObjetivoChanging(string value);
    partial void OnObjetivoChanged();
    #endregion
		
		public ObjetivosNutricionale()
		{
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdObjetivoNutricional", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdObjetivoNutricional
		{
			get
			{
				return this._IdObjetivoNutricional;
			}
			set
			{
				if ((this._IdObjetivoNutricional != value))
				{
					this.OnIdObjetivoNutricionalChanging(value);
					this.SendPropertyChanging();
					this._IdObjetivoNutricional = value;
					this.SendPropertyChanged("IdObjetivoNutricional");
					this.OnIdObjetivoNutricionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKIdUsuario", DbType="Int NOT NULL")]
		public int FKIdUsuario
		{
			get
			{
				return this._FKIdUsuario;
			}
			set
			{
				if ((this._FKIdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._FKIdUsuario = value;
					this.SendPropertyChanged("FKIdUsuario");
					this.OnFKIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeEstablecimiento", DbType="Date NOT NULL")]
		public System.DateTime FechaDeEstablecimiento
		{
			get
			{
				return this._FechaDeEstablecimiento;
			}
			set
			{
				if ((this._FechaDeEstablecimiento != value))
				{
					this.OnFechaDeEstablecimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaDeEstablecimiento = value;
					this.SendPropertyChanged("FechaDeEstablecimiento");
					this.OnFechaDeEstablecimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaloriasDiaObjetivo", DbType="Decimal(10,2) NOT NULL")]
		public decimal CaloriasDiaObjetivo
		{
			get
			{
				return this._CaloriasDiaObjetivo;
			}
			set
			{
				if ((this._CaloriasDiaObjetivo != value))
				{
					this.OnCaloriasDiaObjetivoChanging(value);
					this.SendPropertyChanging();
					this._CaloriasDiaObjetivo = value;
					this.SendPropertyChanged("CaloriasDiaObjetivo");
					this.OnCaloriasDiaObjetivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProteinasDiaObjetivo", DbType="Decimal(10,2) NOT NULL")]
		public decimal ProteinasDiaObjetivo
		{
			get
			{
				return this._ProteinasDiaObjetivo;
			}
			set
			{
				if ((this._ProteinasDiaObjetivo != value))
				{
					this.OnProteinasDiaObjetivoChanging(value);
					this.SendPropertyChanging();
					this._ProteinasDiaObjetivo = value;
					this.SendPropertyChanged("ProteinasDiaObjetivo");
					this.OnProteinasDiaObjetivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarbohidratosDiaObjetivo", DbType="Decimal(10,2) NOT NULL")]
		public decimal CarbohidratosDiaObjetivo
		{
			get
			{
				return this._CarbohidratosDiaObjetivo;
			}
			set
			{
				if ((this._CarbohidratosDiaObjetivo != value))
				{
					this.OnCarbohidratosDiaObjetivoChanging(value);
					this.SendPropertyChanging();
					this._CarbohidratosDiaObjetivo = value;
					this.SendPropertyChanged("CarbohidratosDiaObjetivo");
					this.OnCarbohidratosDiaObjetivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrasasDiaObjetivo", DbType="Decimal(10,2) NOT NULL")]
		public decimal GrasasDiaObjetivo
		{
			get
			{
				return this._GrasasDiaObjetivo;
			}
			set
			{
				if ((this._GrasasDiaObjetivo != value))
				{
					this.OnGrasasDiaObjetivoChanging(value);
					this.SendPropertyChanging();
					this._GrasasDiaObjetivo = value;
					this.SendPropertyChanged("GrasasDiaObjetivo");
					this.OnGrasasDiaObjetivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Objetivo", DbType="VarChar(10)")]
		public string Objetivo
		{
			get
			{
				return this._Objetivo;
			}
			set
			{
				if ((this._Objetivo != value))
				{
					this.OnObjetivoChanging(value);
					this.SendPropertyChanging();
					this._Objetivo = value;
					this.SendPropertyChanged("Objetivo");
					this.OnObjetivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_ObjetivosNutricionale", Storage="_Usuario", ThisKey="FKIdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.ObjetivosNutricionales.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.ObjetivosNutricionales.Add(this);
						this._FKIdUsuario = value.IdUsuario;
					}
					else
					{
						this._FKIdUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserMetrica")]
	public partial class UserMetrica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdMetrica;
		
		private int _FKIdUsuario;
		
		private System.Nullable<System.DateTime> _FechaMedicion;
		
		private System.Nullable<int> _AlturaCM;
		
		private System.Nullable<decimal> _PesoKG;
		
		private System.Nullable<System.DateTime> _FechaNacimiento;
		
		private System.Nullable<char> _Sexo;
		
		private System.Nullable<int> _NivelDeActividad;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMetricaChanging(int value);
    partial void OnIdMetricaChanged();
    partial void OnFKIdUsuarioChanging(int value);
    partial void OnFKIdUsuarioChanged();
    partial void OnFechaMedicionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaMedicionChanged();
    partial void OnAlturaCMChanging(System.Nullable<int> value);
    partial void OnAlturaCMChanged();
    partial void OnPesoKGChanging(System.Nullable<decimal> value);
    partial void OnPesoKGChanged();
    partial void OnFechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaNacimientoChanged();
    partial void OnSexoChanging(System.Nullable<char> value);
    partial void OnSexoChanged();
    partial void OnNivelDeActividadChanging(System.Nullable<int> value);
    partial void OnNivelDeActividadChanged();
    #endregion
		
		public UserMetrica()
		{
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMetrica", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdMetrica
		{
			get
			{
				return this._IdMetrica;
			}
			set
			{
				if ((this._IdMetrica != value))
				{
					this.OnIdMetricaChanging(value);
					this.SendPropertyChanging();
					this._IdMetrica = value;
					this.SendPropertyChanged("IdMetrica");
					this.OnIdMetricaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKIdUsuario", DbType="Int NOT NULL")]
		public int FKIdUsuario
		{
			get
			{
				return this._FKIdUsuario;
			}
			set
			{
				if ((this._FKIdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._FKIdUsuario = value;
					this.SendPropertyChanged("FKIdUsuario");
					this.OnFKIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaMedicion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaMedicion
		{
			get
			{
				return this._FechaMedicion;
			}
			set
			{
				if ((this._FechaMedicion != value))
				{
					this.OnFechaMedicionChanging(value);
					this.SendPropertyChanging();
					this._FechaMedicion = value;
					this.SendPropertyChanged("FechaMedicion");
					this.OnFechaMedicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlturaCM", DbType="Int")]
		public System.Nullable<int> AlturaCM
		{
			get
			{
				return this._AlturaCM;
			}
			set
			{
				if ((this._AlturaCM != value))
				{
					this.OnAlturaCMChanging(value);
					this.SendPropertyChanging();
					this._AlturaCM = value;
					this.SendPropertyChanged("AlturaCM");
					this.OnAlturaCMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PesoKG", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PesoKG
		{
			get
			{
				return this._PesoKG;
			}
			set
			{
				if ((this._PesoKG != value))
				{
					this.OnPesoKGChanging(value);
					this.SendPropertyChanging();
					this._PesoKG = value;
					this.SendPropertyChanged("PesoKG");
					this.OnPesoKGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="Char(1)")]
		public System.Nullable<char> Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelDeActividad", DbType="Int")]
		public System.Nullable<int> NivelDeActividad
		{
			get
			{
				return this._NivelDeActividad;
			}
			set
			{
				if ((this._NivelDeActividad != value))
				{
					this.OnNivelDeActividadChanging(value);
					this.SendPropertyChanging();
					this._NivelDeActividad = value;
					this.SendPropertyChanged("NivelDeActividad");
					this.OnNivelDeActividadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_UserMetrica", Storage="_Usuario", ThisKey="FKIdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.UserMetricas.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.UserMetricas.Add(this);
						this._FKIdUsuario = value.IdUsuario;
					}
					else
					{
						this._FKIdUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alimento")]
	public partial class Alimento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAlimento;
		
		private string _Nombre;
		
		private decimal _Calorias100;
		
		private decimal _Proteinas100;
		
		private decimal _Carbohidratos100;
		
		private decimal _Grasas100;
		
		private string _CodigoBarras;
		
		private string _ImagenUrl;
		
		private EntitySet<ListaIngrediente> _ListaIngredientes;
		
		private EntitySet<AlimentoIngerido> _AlimentoIngeridos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAlimentoChanging(int value);
    partial void OnIdAlimentoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCalorias100Changing(decimal value);
    partial void OnCalorias100Changed();
    partial void OnProteinas100Changing(decimal value);
    partial void OnProteinas100Changed();
    partial void OnCarbohidratos100Changing(decimal value);
    partial void OnCarbohidratos100Changed();
    partial void OnGrasas100Changing(decimal value);
    partial void OnGrasas100Changed();
    partial void OnCodigoBarrasChanging(string value);
    partial void OnCodigoBarrasChanged();
    partial void OnImagenUrlChanging(string value);
    partial void OnImagenUrlChanged();
    #endregion
		
		public Alimento()
		{
			this._ListaIngredientes = new EntitySet<ListaIngrediente>(new Action<ListaIngrediente>(this.attach_ListaIngredientes), new Action<ListaIngrediente>(this.detach_ListaIngredientes));
			this._AlimentoIngeridos = new EntitySet<AlimentoIngerido>(new Action<AlimentoIngerido>(this.attach_AlimentoIngeridos), new Action<AlimentoIngerido>(this.detach_AlimentoIngeridos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlimento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAlimento
		{
			get
			{
				return this._IdAlimento;
			}
			set
			{
				if ((this._IdAlimento != value))
				{
					this.OnIdAlimentoChanging(value);
					this.SendPropertyChanging();
					this._IdAlimento = value;
					this.SendPropertyChanged("IdAlimento");
					this.OnIdAlimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calorias100", DbType="Decimal(8,2) NOT NULL")]
		public decimal Calorias100
		{
			get
			{
				return this._Calorias100;
			}
			set
			{
				if ((this._Calorias100 != value))
				{
					this.OnCalorias100Changing(value);
					this.SendPropertyChanging();
					this._Calorias100 = value;
					this.SendPropertyChanged("Calorias100");
					this.OnCalorias100Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proteinas100", DbType="Decimal(8,2) NOT NULL")]
		public decimal Proteinas100
		{
			get
			{
				return this._Proteinas100;
			}
			set
			{
				if ((this._Proteinas100 != value))
				{
					this.OnProteinas100Changing(value);
					this.SendPropertyChanging();
					this._Proteinas100 = value;
					this.SendPropertyChanged("Proteinas100");
					this.OnProteinas100Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carbohidratos100", DbType="Decimal(8,2) NOT NULL")]
		public decimal Carbohidratos100
		{
			get
			{
				return this._Carbohidratos100;
			}
			set
			{
				if ((this._Carbohidratos100 != value))
				{
					this.OnCarbohidratos100Changing(value);
					this.SendPropertyChanging();
					this._Carbohidratos100 = value;
					this.SendPropertyChanged("Carbohidratos100");
					this.OnCarbohidratos100Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grasas100", DbType="Decimal(8,2) NOT NULL")]
		public decimal Grasas100
		{
			get
			{
				return this._Grasas100;
			}
			set
			{
				if ((this._Grasas100 != value))
				{
					this.OnGrasas100Changing(value);
					this.SendPropertyChanging();
					this._Grasas100 = value;
					this.SendPropertyChanged("Grasas100");
					this.OnGrasas100Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoBarras", DbType="VarChar(50)")]
		public string CodigoBarras
		{
			get
			{
				return this._CodigoBarras;
			}
			set
			{
				if ((this._CodigoBarras != value))
				{
					this.OnCodigoBarrasChanging(value);
					this.SendPropertyChanging();
					this._CodigoBarras = value;
					this.SendPropertyChanged("CodigoBarras");
					this.OnCodigoBarrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagenUrl", DbType="VarChar(500)")]
		public string ImagenUrl
		{
			get
			{
				return this._ImagenUrl;
			}
			set
			{
				if ((this._ImagenUrl != value))
				{
					this.OnImagenUrlChanging(value);
					this.SendPropertyChanging();
					this._ImagenUrl = value;
					this.SendPropertyChanged("ImagenUrl");
					this.OnImagenUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alimento_ListaIngrediente", Storage="_ListaIngredientes", ThisKey="IdAlimento", OtherKey="FKIdAlimento")]
		public EntitySet<ListaIngrediente> ListaIngredientes
		{
			get
			{
				return this._ListaIngredientes;
			}
			set
			{
				this._ListaIngredientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alimento_AlimentoIngerido", Storage="_AlimentoIngeridos", ThisKey="IdAlimento", OtherKey="FKIdAlimento")]
		public EntitySet<AlimentoIngerido> AlimentoIngeridos
		{
			get
			{
				return this._AlimentoIngeridos;
			}
			set
			{
				this._AlimentoIngeridos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ListaIngredientes(ListaIngrediente entity)
		{
			this.SendPropertyChanging();
			entity.Alimento = this;
		}
		
		private void detach_ListaIngredientes(ListaIngrediente entity)
		{
			this.SendPropertyChanging();
			entity.Alimento = null;
		}
		
		private void attach_AlimentoIngeridos(AlimentoIngerido entity)
		{
			this.SendPropertyChanging();
			entity.Alimento = this;
		}
		
		private void detach_AlimentoIngeridos(AlimentoIngerido entity)
		{
			this.SendPropertyChanging();
			entity.Alimento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlimentoIngerido")]
	public partial class AlimentoIngerido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAlimentoIngerido;
		
		private int _FKIdUsuario;
		
		private int _FKIdAlimento;
		
		private System.DateTime _FechaHoraConsumo;
		
		private decimal _CantidadGramos;
		
		private EntityRef<Alimento> _Alimento;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAlimentoIngeridoChanging(int value);
    partial void OnIdAlimentoIngeridoChanged();
    partial void OnFKIdUsuarioChanging(int value);
    partial void OnFKIdUsuarioChanged();
    partial void OnFKIdAlimentoChanging(int value);
    partial void OnFKIdAlimentoChanged();
    partial void OnFechaHoraConsumoChanging(System.DateTime value);
    partial void OnFechaHoraConsumoChanged();
    partial void OnCantidadGramosChanging(decimal value);
    partial void OnCantidadGramosChanged();
    #endregion
		
		public AlimentoIngerido()
		{
			this._Alimento = default(EntityRef<Alimento>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlimentoIngerido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAlimentoIngerido
		{
			get
			{
				return this._IdAlimentoIngerido;
			}
			set
			{
				if ((this._IdAlimentoIngerido != value))
				{
					this.OnIdAlimentoIngeridoChanging(value);
					this.SendPropertyChanging();
					this._IdAlimentoIngerido = value;
					this.SendPropertyChanged("IdAlimentoIngerido");
					this.OnIdAlimentoIngeridoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKIdUsuario", DbType="Int NOT NULL")]
		public int FKIdUsuario
		{
			get
			{
				return this._FKIdUsuario;
			}
			set
			{
				if ((this._FKIdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._FKIdUsuario = value;
					this.SendPropertyChanged("FKIdUsuario");
					this.OnFKIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKIdAlimento", DbType="Int NOT NULL")]
		public int FKIdAlimento
		{
			get
			{
				return this._FKIdAlimento;
			}
			set
			{
				if ((this._FKIdAlimento != value))
				{
					if (this._Alimento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKIdAlimentoChanging(value);
					this.SendPropertyChanging();
					this._FKIdAlimento = value;
					this.SendPropertyChanged("FKIdAlimento");
					this.OnFKIdAlimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraConsumo", DbType="DateTime NOT NULL")]
		public System.DateTime FechaHoraConsumo
		{
			get
			{
				return this._FechaHoraConsumo;
			}
			set
			{
				if ((this._FechaHoraConsumo != value))
				{
					this.OnFechaHoraConsumoChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraConsumo = value;
					this.SendPropertyChanged("FechaHoraConsumo");
					this.OnFechaHoraConsumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadGramos", DbType="Decimal(8,0) NOT NULL")]
		public decimal CantidadGramos
		{
			get
			{
				return this._CantidadGramos;
			}
			set
			{
				if ((this._CantidadGramos != value))
				{
					this.OnCantidadGramosChanging(value);
					this.SendPropertyChanging();
					this._CantidadGramos = value;
					this.SendPropertyChanged("CantidadGramos");
					this.OnCantidadGramosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alimento_AlimentoIngerido", Storage="_Alimento", ThisKey="FKIdAlimento", OtherKey="IdAlimento", IsForeignKey=true)]
		public Alimento Alimento
		{
			get
			{
				return this._Alimento.Entity;
			}
			set
			{
				Alimento previousValue = this._Alimento.Entity;
				if (((previousValue != value) 
							|| (this._Alimento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alimento.Entity = null;
						previousValue.AlimentoIngeridos.Remove(this);
					}
					this._Alimento.Entity = value;
					if ((value != null))
					{
						value.AlimentoIngeridos.Add(this);
						this._FKIdAlimento = value.IdAlimento;
					}
					else
					{
						this._FKIdAlimento = default(int);
					}
					this.SendPropertyChanged("Alimento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_AlimentoIngerido", Storage="_Usuario", ThisKey="FKIdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.AlimentoIngeridos.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.AlimentoIngeridos.Add(this);
						this._FKIdUsuario = value.IdUsuario;
					}
					else
					{
						this._FKIdUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
